[general]
interactive = true
show_fps = false
fps_report_interval_secs = 1
scale_mode = "cover"
force_scene_audio_loop = false

[renderer]
library_path = ""
source = "/path/to/Steam/steamapps/workshop/content/431960/<wallpaper-id>"
assets_path = "/path/to/Steam/steamapps/common/wallpaper_engine/assets"
cache_path = "~/.cache/we-layerd/renderer"
prefer_dmabuf = true
allow_shm_fallback = true
fps = 60
speed = 1.0
volume = 1.0
muted = false
options_json = '''
{
  "example": true
}
'''
